---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
      - name: Pull image
        shell: pip install docker
        docker_image:
          name: tarun0127/calculator:latest
          source: pull
      # - name: Start docker service
      #   service:
      #     name: docker
      #     state: started
      - name: Running container
        shell: docker run -it -d --name Calculator tarun0127/calculator
